# data
img_file: ./data/raw/
train_csv_path: ./data/raw/train.csv
test_csv_path: ./data/raw/test.csv
batch_size: 128
num_workers: 2

# model
num_outputs: 176
model_path: ./model/bs128_ep50_lre-3.pth

# training
num_epochs: 50
lr: 0.001
weight_decay: 0
